steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdemo-preprod', '.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdemo-preprod']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdemo-preprod
  - --location=us-central1-c
  - --cluster=cluster-1
  - --namespace=gcp-devops-preprod