apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gcpdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcpdemo
  template:
    metadata:
      labels:
        app: gcpdemo
    spec:
      containers:
      - name: gcpdemo
        image: gcr.io/gcp-demo-385203/gcpdemo:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: gcpdemo-serivce
  namespace: gcp-devops-prod
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  type: LoadBalancer
  selector:
    app: gcpdemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
 
